[2020-07-16 18:28:34,499] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-16T12:56:09.202130+00:00 [queued]>
[2020-07-16 18:28:34,511] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-16T12:56:09.202130+00:00 [queued]>
[2020-07-16 18:28:34,511] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-16 18:28:34,511] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-07-16 18:28:34,511] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-16 18:28:34,693] {taskinstance.py:900} INFO - Executing <Task(BashOperator): db1_to_csv> on 2020-07-16T12:56:09.202130+00:00
[2020-07-16 18:28:34,699] {standard_task_runner.py:53} INFO - Started process 873964 to run task
[2020-07-16 18:28:35,027] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.db1_to_csv 2020-07-16T12:56:09.202130+00:00 [running]> bhakti-Vostro-3558
[2020-07-16 18:28:35,040] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-16 18:28:35,041] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpn2q2q6j9/db1_to_csvvbqdagr_
[2020-07-16 18:28:35,041] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=root
dbname=airflow_db1
host=mysql
port=3306
docker exec -it mysqlCon \
mysql -D$dbname -h$host -p$port -u$user -p$password -e'SELECT * FROM employees INTO OUTFILE "/input_files_mysql/sample3.csv" FIELDS ENCLOSED BY '"' TERMINATED BY "," ESCAPED BY '"' LINES TERMINATED BY "\n";'
[2020-07-16 18:28:35,049] {bash_operator.py:122} INFO - Output:
[2020-07-16 18:28:35,622] {bash_operator.py:126} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2020-07-16 18:28:35,639] {bash_operator.py:126} INFO - ERROR 1086 (HY000) at line 1: File '/input_files_mysql/sample3.csv' already exists
[2020-07-16 18:28:35,690] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-07-16 18:28:35,697] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-16 18:28:35,699] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=storing_data, task_id=db1_to_csv, execution_date=20200716T125609, start_date=20200716T125834, end_date=20200716T125835
[2020-07-16 18:28:44,382] {logging_mixin.py:112} INFO - [2020-07-16 18:28:44,382] {local_task_job.py:103} INFO - Task exited with return code 1
