[2020-08-26 12:00:59,732] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.mysql_to_csv 2020-08-25T06:20:03.393737+00:00 [queued]>
[2020-08-26 12:00:59,745] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.mysql_to_csv 2020-08-25T06:20:03.393737+00:00 [queued]>
[2020-08-26 12:00:59,746] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-08-26 12:00:59,747] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-08-26 12:00:59,747] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-08-26 12:00:59,977] {taskinstance.py:900} INFO - Executing <Task(MySqlOperator): mysql_to_csv> on 2020-08-25T06:20:03.393737+00:00
[2020-08-26 12:00:59,981] {standard_task_runner.py:53} INFO - Started process 82122 to run task
[2020-08-26 12:01:00,197] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: employees_dag.mysql_to_csv 2020-08-25T06:20:03.393737+00:00 [running]> bhakti-Vostro-3558
[2020-08-26 12:01:00,216] {mysql_operator.py:61} INFO - Executing: SELECT * FROM employees INTO OUTFILE "/input_files_mysql/sample4.csv"
FIELDS ENCLOSED BY '"' TERMINATED BY ',' ESCAPED BY '"' LINES TERMINATED BY "\n";
[2020-08-26 12:01:00,268] {logging_mixin.py:112} INFO - [2020-08-26 12:01:00,267] {base_hook.py:87} INFO - Using connection to: id: local_mysql. Host: localhost, Port: None, Schema: airflow, Login: airflow, Password: XXXXXXXX, extra: None
[2020-08-26 12:01:00,270] {taskinstance.py:1145} ERROR - (1045, "Access denied for user 'airflow'@'172.22.0.1' (using password: YES)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/mysql_operator.py", line 64, in execute
    hook.run(
  File "/usr/local/lib/python3.8/dist-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.8/dist-packages/airflow/hooks/mysql_hook.py", line 116, in get_conn
    conn = MySQLdb.connect(**conn_config)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'airflow'@'172.22.0.1' (using password: YES)")
[2020-08-26 12:01:00,312] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=employees_dag, task_id=mysql_to_csv, execution_date=20200825T062003, start_date=20200826T063059, end_date=20200826T063100
[2020-08-26 12:01:09,578] {logging_mixin.py:112} INFO - [2020-08-26 12:01:09,578] {local_task_job.py:103} INFO - Task exited with return code 1
