[2020-07-13 17:14:58,934] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.check_file_exists 2020-07-13T11:41:44.798036+00:00 [queued]>
[2020-07-13 17:14:58,944] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.check_file_exists 2020-07-13T11:41:44.798036+00:00 [queued]>
[2020-07-13 17:14:58,945] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 17:14:58,945] {taskinstance.py:880} INFO - Starting attempt 3 of 3
[2020-07-13 17:14:58,945] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 17:14:59,076] {taskinstance.py:900} INFO - Executing <Task(BashOperator): check_file_exists> on 2020-07-13T11:41:44.798036+00:00
[2020-07-13 17:14:59,082] {standard_task_runner.py:53} INFO - Started process 31634 to run task
[2020-07-13 17:14:59,274] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: employees_dag.check_file_exists 2020-07-13T11:41:44.798036+00:00 [running]> bhakti-Vostro-3558
[2020-07-13 17:14:59,301] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-13 17:14:59,303] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmposk4h_3f/check_file_existsl4afd7t9
[2020-07-13 17:14:59,303] {bash_operator.py:115} INFO - Running command: . /home/bhakti/airflow/input_data/sample.csv
[2020-07-13 17:14:59,316] {bash_operator.py:122} INFO - Output:
[2020-07-13 17:14:59,320] {bash_operator.py:126} INFO - /home/bhakti/airflow/input_data/sample.csv: line 1: PERSON,JOINING_YEAR,COMPANY: command not found
[2020-07-13 17:14:59,321] {bash_operator.py:126} INFO - /home/bhakti/airflow/input_data/sample.csv: line 2: John,2018,Google: command not found
[2020-07-13 17:14:59,322] {bash_operator.py:126} INFO - /home/bhakti/airflow/input_data/sample.csv: line 3: Sam,2017,IBM: command not found
[2020-07-13 17:14:59,323] {bash_operator.py:126} INFO - /home/bhakti/airflow/input_data/sample.csv: line 4: Jeff,2014,Yahoo: command not found
[2020-07-13 17:14:59,327] {bash_operator.py:126} INFO - /home/bhakti/airflow/input_data/sample.csv: line 5: Allen,2015,Facebook: command not found
[2020-07-13 17:14:59,330] {bash_operator.py:128} INFO - Command exited with return code 127
[2020-07-13 17:14:59,345] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-13 17:14:59,348] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=employees_dag, task_id=check_file_exists, execution_date=20200713T114144, start_date=20200713T114458, end_date=20200713T114459
[2020-07-13 17:15:08,819] {logging_mixin.py:112} INFO - [2020-07-13 17:15:08,819] {local_task_job.py:103} INFO - Task exited with return code 1
