[2020-07-18 12:15:17,464] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-17T00:00:00+00:00 [queued]>
[2020-07-18 12:15:17,473] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-17T00:00:00+00:00 [queued]>
[2020-07-18 12:15:17,473] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 12:15:17,473] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-18 12:15:17,473] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 12:15:17,625] {taskinstance.py:900} INFO - Executing <Task(BashOperator): db1_to_csv> on 2020-07-17T00:00:00+00:00
[2020-07-18 12:15:17,630] {standard_task_runner.py:53} INFO - Started process 9116 to run task
[2020-07-18 12:15:17,845] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.db1_to_csv 2020-07-17T00:00:00+00:00 [running]> bhakti-Vostro-3558
[2020-07-18 12:15:17,860] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-18 12:15:17,861] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpcapa90w7/db1_to_csvokj7uqe3
[2020-07-18 12:15:17,861] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=root
dbname=airflow_db1
host=mysql
port=3306
docker exec -it mysqlCon \
mysql -D$dbname -h$host -p$port -u$user -p$password -e'SELECT * FROM employees INTO OUTFILE "/input_files_mysql/sample1.csv" FIELDS TERMINATED BY "," LINES TERMINATED BY "\r\n";'
[2020-07-18 12:15:17,867] {bash_operator.py:122} INFO - Output:
[2020-07-18 12:15:20,004] {bash_operator.py:126} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2020-07-18 12:15:25,365] {bash_operator.py:126} INFO - ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (22)
[2020-07-18 12:15:25,406] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-07-18 12:15:25,414] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-18 12:15:25,562] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-18 12:15:27,303] {logging_mixin.py:112} INFO - [2020-07-18 12:15:27,302] {local_task_job.py:103} INFO - Task exited with return code 1
