[2020-07-13 10:51:29,377] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.create_mysql_table 2020-07-13T05:20:07.436675+00:00 [queued]>
[2020-07-13 10:51:29,386] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.create_mysql_table 2020-07-13T05:20:07.436675+00:00 [queued]>
[2020-07-13 10:51:29,386] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 10:51:29,386] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-07-13 10:51:29,386] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 10:51:29,645] {taskinstance.py:900} INFO - Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-13T05:20:07.436675+00:00
[2020-07-13 10:51:29,650] {standard_task_runner.py:53} INFO - Started process 16994 to run task
[2020-07-13 10:51:29,908] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: employees_dag.create_mysql_table 2020-07-13T05:20:07.436675+00:00 [running]> bhakti-Vostro-3558
[2020-07-13 10:51:29,920] {mysql_operator.py:61} INFO - Executing: CREATE TABLE [IF NOT EXISTS] employees_data(PERSON VARCHAR(30),JOINING_YEAR DOUBLE, COMPANY VARCHAR(30));
[2020-07-13 10:51:29,965] {logging_mixin.py:112} INFO - [2020-07-13 10:51:29,965] {base_hook.py:87} INFO - Using connection to: id: mysql_conn. Host: localhost, Port: None, Schema: mysql, Login: root, Password: XXXXXXXX, extra: None
[2020-07-13 10:51:29,968] {logging_mixin.py:112} INFO - [2020-07-13 10:51:29,967] {dbapi_hook.py:174} INFO - CREATE TABLE [IF NOT EXISTS] employees_data(PERSON VARCHAR(30),JOINING_YEAR DOUBLE, COMPANY VARCHAR(30));
[2020-07-13 10:51:29,968] {taskinstance.py:1145} ERROR - (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] employees_data(PERSON VARCHAR(30),JOINING_YEAR DOUBLE, COMPANY V' at line 1")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/mysql_operator.py", line 64, in execute
    hook.run(
  File "/usr/local/lib/python3.8/dist-packages/airflow/hooks/dbapi_hook.py", line 175, in run
    cur.execute(s)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] employees_data(PERSON VARCHAR(30),JOINING_YEAR DOUBLE, COMPANY V' at line 1")
[2020-07-13 10:51:29,970] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=employees_dag, task_id=create_mysql_table, execution_date=20200713T052007, start_date=20200713T052129, end_date=20200713T052129
[2020-07-13 10:51:39,247] {logging_mixin.py:112} INFO - [2020-07-13 10:51:39,246] {local_task_job.py:103} INFO - Task exited with return code 1
