[2020-07-10 19:08:34,868] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.check_file_exists 2020-07-10T13:35:30.080082+00:00 [queued]>
[2020-07-10 19:08:34,876] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: employees_dag.check_file_exists 2020-07-10T13:35:30.080082+00:00 [queued]>
[2020-07-10 19:08:34,876] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-10 19:08:34,876] {taskinstance.py:880} INFO - Starting attempt 3 of 3
[2020-07-10 19:08:34,876] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-10 19:08:35,028] {taskinstance.py:900} INFO - Executing <Task(BashOperator): check_file_exists> on 2020-07-10T13:35:30.080082+00:00
[2020-07-10 19:08:35,033] {standard_task_runner.py:53} INFO - Started process 9171 to run task
[2020-07-10 19:08:35,193] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: employees_dag.check_file_exists 2020-07-10T13:35:30.080082+00:00 [running]> bhakti-Vostro-3558
[2020-07-10 19:08:35,205] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-10 19:08:35,206] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpt5x9o_ve/check_file_existsvptioyx6
[2020-07-10 19:08:35,206] {bash_operator.py:115} INFO - Running command: shasum ~/input_data/sample.csv
[2020-07-10 19:08:35,212] {bash_operator.py:122} INFO - Output:
[2020-07-10 19:08:35,247] {bash_operator.py:126} INFO - shasum: /home/bhakti/input_data/sample.csv: No such file or directory
[2020-07-10 19:08:35,248] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-07-10 19:08:35,254] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-10 19:08:35,256] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=employees_dag, task_id=check_file_exists, execution_date=20200710T133530, start_date=20200710T133834, end_date=20200710T133835
[2020-07-10 19:08:44,748] {logging_mixin.py:112} INFO - [2020-07-10 19:08:44,748] {local_task_job.py:103} INFO - Task exited with return code 1
